name: Deploy Lambda

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build jar
        run: ./gradlew clean shadowJar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID}}:role/${{ env.AWS_GITHUB_PERMISSIONS_ROLE_NAME }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Upload jar to S3
        run: |
          aws s3 cp build/libs/lambda-data-parser-0.1-all.jar s3://aws-labmda-deploy/lambda-function.jar

      - name: Update Lambda Function Code
        run: |
          aws lambda update-function-code \
            --function-name my-lambda-function \
            --s3-bucket ${{ env.BUCKET_NAME }}  \
            --s3-key lambda-function.jar \
            --handler com.bodax.home.LambdaMainHandler \
            --runtime java21